### ISSUE TITLE
Feature Request: `font-weight` notation

### ISSUE THREAD

**Issue by tysongach** [sds/scss-lint#741]
Specify a preference of CSS keyword values (`normal`, `bold`, etc…) or numeric values (`400`, `600`, etc…).

Could be similar to [`HexNotation`](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexnotation):

``` yaml
HexNotation:
  enabled: true
  style: numeric # or 'keyword'
```
