### ISSUE TITLE
PseudoElement does not work with ::placeholder property

### ISSUE THREAD

**Issue by shiftgeist** [sds/scss-lint#965]
.scss-lint.yml (Using version 0.5.0)
```yml
PseudoElement:
    enabled: true
```

Error Message: `PseudoElement: Begin pseudo classes with a single colon: ':'`

Code:
```scss
&::placeholder {
    color: blue;
}
```

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) says: The placeholder property is written with two colons.
