### ISSUE TITLE
Problems with scrollbar-color

### ISSUE THREAD

**Issue by RivenSkaye** [sds/scss-lint#994]
scss-lint can at the same time both recognize the proper ordering for `scrollbar-color` and  `scrollbar-width`, but it also tells me it has no idea what `scrollbar-color` is and that it's most probably a spelling error. See the attached image for the simultaneous warnings.
[`scrollbar-color` on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color)
![image](https://user-images.githubusercontent.com/14993038/174437139-156f2db7-d1c9-4e6f-9ec5-f789d4574fab.png)

(S)CSS causing the issue:
```css
table {
    border-collapse: collapse;
    margin: 0 auto;
    max-width: 85%;
    min-width: 60%;
    overflow-x: scroll;
    scrollbar-width: thin;
    scrollbar-color: $scrollbarcolor;

    th {
      background-color: $thbg;
      text-align: center;
    }

    tr:nth-child(even) {
      background-color: $theven;
    }

    td,
	th {
      border: 1px solid $tableborder;
      padding: 3px;
    }
  }
  ```
